admin:
  access_log_path: "/dev/stdout"
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901}

dynamic_resources:
  ads_config:
    api_type: GRPC
    grpc_services:
      envoy_grpc:
        cluster_name: xds_cluster
  cds_config: { ads: {}}

stats_config:
  stats_matcher:
    inclusion_list:
      patterns:
        - regex: "cluster.*version"
        - regex: "server.*"


static_resources:
  listeners:
  - name: egress
    address:
      socket_address: { address: 0.0.0.0, port_value: 9002 }
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: egress_http
          codec_type: AUTO
          rds:
            route_config_name: egress_route
            config_source:
              ads: {}

  clusters:
  - name: xds_cluster
    connect_timeout: 0.25s
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    http2_protocol_options: {}
    hosts: [{ socket_address: { address: "control-plane", port_value: 10000}}]
